config/routes.rb
Rails.application.routes.draw do
  # Root
  root 'pages#index'

  # PagesController routes
  get 'pages/index'
  get 'pages/about'

  # Devise routes
  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: 'register'
    get 'sign-in', to: 'devise/sessions#new', as: 'sign_in'
  end

  #Resource
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :timeslots, only: [ :index, :show, :update ]
  end
end

app/models/acadyear.rb
class Acadyear < ActiveRecord::Base
  has_many :semesters
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :acadyear
  has_many :timeslots
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  belongs_to :user
  belongs_to :semester
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :timeslots
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/timeslot_controller.rb
module API
  class TimeslotController < ApplicationController
    def index
      ts = current_user.timeslots

      repond_to do |format|
        format.json
      end
    end

    def show
      t = Timeslot.find(params[:id])

      respond_to do |format|
        format.json
      end
    end

    def update
      @timeslots = current_user.timeslots
      current_no = @timeslots.count
      update_no = timeslot_params.count

      if (current_no < update_no)
        (0..current_no - 1).each do |i|
          @timeslots[i].update_attributes(timeslot_params[i])
          @timeslots[i].save
        end
      else
        (current_no..update_no - 1).each do |i|
          @timeslots[i] = current_user.timeslots.build(timeslots_params[i])
          @timeslots[i].save
        end
      end


      respond_to do |format|
        format.json
      end
    end

    private
      def timeslot_params
        params.require(:timeslots)
      end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/timeslot_helper.rb
module TimeslotHelper
end

app/views/layouts/_view_specific_javascript.html.haml
- if @view_js && !@view_js.empty?
  - @view_js.each do |j|
    = javascript_include_tag j

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Elvis"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:400,600,300"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = render "layouts/view_specific_javascript"

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.erb

app/views/pages/index.html.haml
-# include view specific js
- @view_js = ['pages/index']
%header.container
  .top-bar
    = link_to root_path, class: 'logo' do
      .logo-img
        = image_tag 'shared/logo.svg', alt: 'Elvis', class: 'responsive'
      .logo-text
        %h1 Elvis
    #modules-mount-point
    %nav
      = link_to 'Features', '#'
      = link_to 'Sign In', sign_in_path
      = link_to 'Register', register_path, class: 'action'

%section.splash-section.container.absolute
  %h2
    Planning for your NUS modules
    %br/
    has never been this easy.
  = link_to '#' do
    %button.action#start-now
      Start Now

%section.main-section.container.absolute
  .modules-display
    %h2 Selected Modules
    #modules-display-mount-point
  .timetable-display#timetable-mount-point

.loading-box
  .loading-screen
  .loading-items-container
    %i.fa.fa-circle-o-notch.fa-spin
    .loading-text Loading